#!/bin/sh

table=catalog_sales
rm -f *.dat
curr_path=`pwd`
export LD_LIBRARY_PATH=$curr_path/src/main/resources ; java --enable-native-access=ALL-UNNAMED -jar ./target/tpcds-1.5-SNAPSHOT-jar-with-dependencies.jar --scale 1 --table $table

