/*
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package io.trino.tpcds.column.generator;

import io.trino.tpcds.Table;
import io.trino.tpcds.column.Column;
import io.trino.tpcds.column.ColumnType;

import static io.trino.tpcds.Table.STORE_SALES;
import static io.trino.tpcds.column.ColumnTypes.DECIMAL;
import static io.trino.tpcds.column.ColumnTypes.DECIMAL_LAYOUT;
import static io.trino.tpcds.column.ColumnTypes.IDENTIFIER;
import static io.trino.tpcds.column.ColumnTypes.INTEGER;

public enum StoreSalesNativeGeneratorColumn
        implements Column
{
    SS_SOLD_DATE_SK(IDENTIFIER),
    SS_SOLD_TIME_SK(IDENTIFIER),
    SS_SOLD_ITEM_SK(IDENTIFIER),
    SS_SOLD_CUSTOMER_SK(IDENTIFIER),
    SS_SOLD_CDEMO_SK(IDENTIFIER),
    SS_SOLD_HDEMO_SK(IDENTIFIER),
    SS_SOLD_ADDR_SK(IDENTIFIER),
    SS_SOLD_STORE_SK(IDENTIFIER),
    SS_SOLD_PROMO_SK(IDENTIFIER),
    SS_TICKET_NUMBER(IDENTIFIER),
    SS_PRICING_WHOLESALE_COST_NUMBER(DECIMAL),
    SS_PRICING_WHOLESALE_COST_PRECISION(INTEGER),
    SS_PRICING_WHOLESALE_COST_SCALE(INTEGER),
    SS_PRICING_WHOLESALE_COST_FLAGS(INTEGER),
    SS_PADDING_INT1(INTEGER),
    SS_PRICING_LIST_PRICE_NUMBER(DECIMAL),
    SS_PRICING_LIST_PRICE_PRECISION(INTEGER),
    SS_PRICING_LIST_PRICE_SCALE(INTEGER),
    SS_PRICING_LIST_PRICE_FLAGS(INTEGER),
    SS_PADDING_INT2(INTEGER),
    SS_PRICING_SALES_PRICE_NUMBER(DECIMAL),
    SS_PRICING_SALES_PRICE_PRECISION(INTEGER),
    SS_PRICING_SALES_PRICE_SCALE(INTEGER),
    SS_PRICING_SALES_PRICE_FLAGS(INTEGER),
    SS_PADDING_INT3(INTEGER),
    SS_PRICING_EXT_DISCOUNT_AMOUNT_NUMBER(DECIMAL),
    SS_PRICING_EXT_DISCOUNT_AMOUNT_PRECISION(INTEGER),
    SS_PRICING_EXT_DISCOUNT_AMOUNT_SCALE(INTEGER),
    SS_PRICING_EXT_DISCOUNT_AMOUNT_FLAGS(INTEGER),
    SS_PADDING_INT4(INTEGER),
    SS_PRICING_EXT_SALES_PRICE_NUMBER(DECIMAL),
    SS_PRICING_EXT_SALES_PRICE_PRECISION(INTEGER),
    SS_PRICING_EXT_SALES_PRICE_SCALE(INTEGER),
    SS_PRICING_EXT_SALES_PRICE_FLAGS(INTEGER),
    SS_PADDING_INT5(INTEGER),
    SS_PRICING_EXT_WHOLESALE_COST_NUMBER(DECIMAL),
    SS_PRICING_EXT_WHOLESALE_COST_PRECISION(INTEGER),
    SS_PRICING_EXT_WHOLESALE_COST_SCALE(INTEGER),
    SS_PRICING_EXT_WHOLESALE_COST_FLAGS(INTEGER),
    SS_PADDING_INT6(INTEGER),
    SS_PRICING_EXT_LIST_PRICE_NUMBER(DECIMAL),
    SS_PRICING_EXT_LIST_PRICE_PRECISION(INTEGER),
    SS_PRICING_EXT_LIST_PRICE_SCALE(INTEGER),
    SS_PRICING_EXT_LIST_PRICE_FLAGS(INTEGER),
    SS_PADDING_INT7(INTEGER),
    SS_PRICING_TAX_PCT_NUMBER(DECIMAL),
    SS_PRICING_TAX_PCT_PRECISION(INTEGER),
    SS_PRICING_TAX_PCT_SCALE(INTEGER),
    SS_PRICING_TAX_PCT_FLAGS(INTEGER),
    SS_PADDING_INT8(INTEGER),
    SS_PRICING_COUPON_AMT_NUMBER(DECIMAL),
    SS_PRICING_COUPON_AMT_PRECISION(INTEGER),
    SS_PRICING_COUPON_AMT_SCALE(INTEGER),
    SS_PRICING_COUPON_AMT_FLAGS(INTEGER),
    SS_PADDING_INT9(INTEGER),
    SS_PRICING_SHIP_COST_NUMBER(DECIMAL),
    SS_PRICING_SHIP_COST_PRECISION(INTEGER),
    SS_PRICING_SHIP_COST_SCALE(INTEGER),
    SS_PRICING_SHIP_COST_FLAGS(INTEGER),
    SS_PADDING_INT10(INTEGER),
    SS_PRICING_NET_PAID_INC_SHIP_NUMBER(DECIMAL),
    SS_PRICING_NET_PAID_INC_SHIP_PRECISION(INTEGER),
    SS_PRICING_NET_PAID_INC_SHIP_SCALE(INTEGER),
    SS_PRICING_NET_PAID_INC_SHIP_FLAGS(INTEGER),
    SS_PADDING_INT11(INTEGER),
    SS_PRICING_NET_PAID_INC_SHIP_TAX_NUMBER(DECIMAL),
    SS_PRICING_NET_PAID_INC_SHIP_TAX_PRECISION(INTEGER),
    SS_PRICING_NET_PAID_INC_SHIP_TAX_SCALE(INTEGER),
    SS_PRICING_NET_PAID_INC_SHIP_TAX_FLAGS(INTEGER),
    SS_PADDING_INT12(INTEGER),
    SS_PRICING_NET_PROFIT_NUMBER(DECIMAL),
    SS_PRICING_NET_PROFIT_PRECISION(INTEGER),
    SS_PRICING_NET_PROFIT_SCALE(INTEGER),
    SS_PRICING_NET_PROFIT_FLAGS(INTEGER),
    SS_PADDING_INT13(INTEGER),
    SS_PRICING_NET_PAID_NUMBER(DECIMAL),
    SS_PRICING_NET_PAID_PRECISION(INTEGER),
    SS_PRICING_NET_PAID_SCALE(INTEGER),
    SS_PRICING_NET_PAID_FLAGS(INTEGER),
    SS_PADDING_INT14(INTEGER),
    SS_PRICING_NET_PAID_INC_TAX_NUMBER(DECIMAL),
    SS_PRICING_NET_PAID_INC_TAX_PRECISION(INTEGER),
    SS_PRICING_NET_PAID_INC_TAX_SCALE(INTEGER),
    SS_PRICING_NET_PAID_INC_TAX_FLAGS(INTEGER),
    SS_PADDING_INT15(INTEGER),
    SS_PRICING_EXT_TAX_NUMBER(DECIMAL),
    SS_PRICING_EXT_TAX_PRECISION(INTEGER),
    SS_PRICING_EXT_TAX_SCALE(INTEGER),
    SS_PRICING_EXT_TAX_FLAGS(INTEGER),
    SS_PADDING_INT16(INTEGER),
    SS_PRICING_EXT_SHIP_COST_NUMBER(DECIMAL),
    SS_PRICING_EXT_SHIP_COST_PRECISION(INTEGER),
    SS_PRICING_EXT_SHIP_COST_SCALE(INTEGER),
    SS_PRICING_EXT_SHIP_COST_FLAGS(INTEGER),
    SS_PADDING_INT17(INTEGER),
    SS_PRICING_QUANTITY(INTEGER),
    SS_VALID(INTEGER),
    SS_PADDING_DECIMAL1(DECIMAL_LAYOUT),
    SS_PADDING_DECIMAL2(DECIMAL_LAYOUT),
    SS_PADDING_DECIMAL3(DECIMAL_LAYOUT),
    SS_PADDING_DECIMAL4(DECIMAL_LAYOUT),
    SS_PADDING_DECIMAL5(DECIMAL_LAYOUT);

    private final ColumnType type;

    StoreSalesNativeGeneratorColumn(ColumnType type)
    {
        this.type = type;
    }

    @Override
    public Table getTable()
    {
        return STORE_SALES;
    }

    @Override
    public String getName()
    {
        return name().toLowerCase();
    }

    @Override
    public ColumnType getType()
    {
        return type;
    }

    @Override
    public int getPosition()
    {
        return ordinal();
    }
}
