#!/bin/sh

scale=$2
results=$1
table=$3

mkdir -p $results/sf$scale/$table
cd ../../../target
curr_dir=`pwd`
cd $results/sf$scale/$table/
java --enable-native-access=ALL-UNNAMED -jar $curr_dir/tpcds-1.5-SNAPSHOT-jar-with-dependencies.jar --scale $scale --directory $results/sf$scale/$table --table $table
echo "sf$scale/$table completed"
