#!/bin/sh

scale=$2
results=$1
table=$3

mkdir -p $results/sf$scale/$table
cd ../../../src/main/resources/dsgen
./dsdgen -scale $scale -dir $results/sf$scale/$table -table $table
cd - > /dev/null
echo "sf$scale/$table completed"
