#!/bin/sh

results=$1

export LD_LIBRARY_PATH=../src/main/resources/dsgen ; time ./gen_catalog_java $results 1 
export LD_LIBRARY_PATH=../src/main/resources/dsgen ; time ./gen_catalog_java $results 10
#export LD_LIBRARY_PATH=../src/main/resources/dsgen ; time ./gen_catalog_java $results 100
